import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Img from '../assets/images/illidanbg.jpg';

import Navbar from "@/components/client/Navbar";
import Header from '../components/client/Each/Header';
import Footer from '../components/client/Each/Footer';
import BottomShadow from "@/components/client/Each/BottomShadow";
import Shadows from "@/components/client/Shadows";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(children);
  return (
    <html lang="en">
      <body
        // style={{background: Img}}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Shadows/>
        <Navbar/>
        {children}
        {/* <BottomShadow/> */}
      </body>
    </html>
  );
}
